### ISSUE TITLE
Support disk-less mode

### ISSUE THREAD

**Issue by peterbourgon** [dgraph-io/badger#1001]
Can BadgerDB support a pure in-memory mode, where there is no disk access at all?

[Related discuss.dgraph.io thread](https://discuss.dgraph.io/t/badgerdb-without-touching-disk/4945).

**Comment by jarifibrahim** [comment]
@peterbourgon We don't support this right now. The value log acts as a WAL which has to be written to the disk.
We might support a memory-only mode in future.

**Comment by manishrjain** [comment]
I think @balajijinnah is working on making it so that if writes don't need to be present in value log (values are already stored in the LSM tree), they won't be written to the log. That change along with setting very high ValueThreshold should give us the ability to not write to value log at all. Then all we need to do is to keep Tables in memory, which is already an option.

Furthermore, if no persistence is required, we can add another option to keep all levels in memory, instead of them being written to disk. This feature could also be useful to allow Dgraph to act like a search engine instead of just a DB.

**Comment by AgentZombie** [comment]
I'm interested in this capability for the purpose of writing unit tests for code that uses badger and would like to avoid those tests depending on having access to write to the disk.
