### ISSUE TITLE
When will badger v2.0 be released?

### ISSUE THREAD

**Issue by yangzh-deepmap** [dgraph-io/badger#1041]
### What version of Badger are you using?
N/A

### What did you expect to see?

badger v2.0 release pretty soon. 

### What did you see instead?
v2.0 has been pending for 2+ months, and we are blocked by it as the data format is not compatible between v1.6 and v2.0: we would like to skip v1.6 directly, but there is no official v2.0 yet.

**Comment by manishrjain** [comment]
I think we should now be ready for a v2.0 cut. Both Encryption and Compression are almost done features.

**Comment by yangzh-deepmap** [comment]
Thanks, and looking forward to official v2.0 release! 

way to go, team!

**Comment by PaluMacil** [comment]
Thanks both of you for the question and answer! I keep checking the releases page every couple days since the blog post seemed to indicate it would be sooner but it makes sense that this was an extraordinarily busy last two months from everything the company has been working on! 😁 Congrats on everything. Looking forward to more

**Comment by yangzh** [comment]
Hey, badger: 

It has been almost one month, and if there any progress on this issue? thanks.
