### ISSUE TITLE
[question] How to add value to already stored uint64, without periodical goroutine

### ISSUE THREAD

**Issue by 1337hax** [dgraph-io/badger#1128]
I'm using Badger 1.6 and have following situation:
1)  I have stored value like this: db["somekey"] = 1000; // some uint64
2) I would like to be able to add as quickly as possible some value to that stored uint64 (another number, e.g. 1000 + 200 = 1200). Quickly in terms of performance, but also to minimize contention - as there might be many threads adding to that value, and I would like to minimize time spent during locks (if there will be any).

Now, I see some example of `GetMergeOperator ` in the docs, which seems to be a solution here, but it's invoked like this: `db.GetMergeOperator(key, add, 200*time.Millisecond)`

The last parameter is very baffling for me: It's some duration, described in the docs like this: 

> The duration specifies how often the merge function is run on values that have been added using the MergeOperator.Add() method.

 In the source code, we can read about that `GetMergeOperator` that it 
> "also fires off a goroutine that performs a compaction using the merge function that runs periodically, as specified by dur.

So, it seems that it will create some goroutine, which will perform this addition in the background indefinitely, with interval specified in the last parameter.  And I would like to not fire any periodical goroutine, just one time atomic add, without loosing consistency if there are many threads trying to add to the same value. 

What would be the recommended solution?

**Comment by shekarm** [comment]
Hi,


Thank you for the question. One of our engineers is looking at this question and you should have a response soon.

—
Shekar Mantha



https://dgraph.io

--- original message ---
On November 19, 2019, 2:17 PM EST notifications@github.com wrote:


I'm using Badger 1.6 and have following situation:

I have stored value like this: db["somekey"] = 1000; // some uint64

I would like to be able to add as quickly as possible some value to that stored uint64 (another number, e.g. 1000 + 200 = 1200). Quickly in terms of performance, but also to minimize contention - as there might be many threads adding to that value, and I would like to minimize time spent during locks (if there will be any).


Now, I see some example of GetMergeOperator in the docs, which seems to be a solution here, but it's invoked like this: db.GetMergeOperator(key, add, 200*time.Millisecond)

The last parameter is very baffling for me: It's some duration, described in the docs like this: "The duration specifies how often the merge function is run on values that have been added using the MergeOperator.Add() method." In the source code, we can write about that GetMergeOperator that it "also fires off a goroutine that performs a compaction using the merge function that runs periodically, as specified by dur."

So, it seems that it will create some goroutine, which will perform this addition in the background indefinitely, with interval specified in the last parameter. And I would like to not fire any periodical goroutine, just one time atomic add, without loosing consistency if there are many threads trying to add to the same value.

What would be the recommended solution?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by burmanm** [comment]
1337hax, wouldn't it be enough to keep all versions and then when fetching the value, fetch all the versions? You could manual merging at some points by doing a read-write transaction thus making sure the transaction boundaries will return conflict if something updated the values meanwhile (and then retry).

**Comment by 1337hax** [comment]
@burmanm, unfortunately, I would like to have multiple threads updating this value quite frequently (adding various numbers to already stored number). So, if I would be doing full read-write transaction, many threads would get their transactions rejected, then they would need to try again, get rejected again etc. However, the feature of badger I mentioned in the original post (GetMergeOperator), seems to be perfect solution - the only undesirable thing is that periodical goroutine which gets spawned basing on the last parameter (from what I understood from the docs). And I would like to perform merging once, without spawning that additional goroutine. Maybe there is some way to just merge values one time?
