### ISSUE TITLE
Can't run race condition tests

### ISSUE THREAD

**Issue by ntrrg** [dgraph-io/badger#1129]
Hello, I am using Bleve v2.0.0 on linux without zstd for compression, but running race condition tests requires `CGO_ENABLED=1` and that gives me a gcc ld error. I already set compression to snappy manually, but it keeps printing gcc ld errors. Is there a way an fix this?

**Comment by jarifibrahim** [comment]
The tests like these https://github.com/dgraph-io/badger/blob/fb0cdb858c78004b9db8f08e91bb713780b20445/table/builder_test.go#L36-L42 require ZSTD since it's hardcoded it.

You can replace ZSTD with Snappy if you're trying to run the tests locally. Something like `sed -i 's/old-text/new-text/g' input.txt` should help.

Feel free to reopen if you think there's something we can do in badger.

**Comment by ntrrg** [comment]
Sorry, I didn't explain that very well :sweat_smile: I was using Badger v1 in my project and running my tests with the `-race` flag worked, now with Badger v2 it prints the gcc errors, but I am not using ZSTD

**Comment by jarifibrahim** [comment]
Hey @ntrrg ! Do you have a test I can look it? If you're not using badger with CGO, it shouldn't complain about `gcc`. 

Please point me to a test that fails with the `gcc` error and I'll try to figure out why it's failing.

**Comment by ntrrg** [comment]
Actually it is working now, I set the crompession in the wrong place, so it was my mistake, sorry about that. Thanks for your time! :)

This fixed the issue: https://github.com/ntrrg/usersd/blob/master/pkg/sdb/options.go#L49
