### ISSUE TITLE
Unbounded disk growth when lots of additions and deletions of keys

### ISSUE THREAD

**Issue by connorgorman** [dgraph-io/badger#1158]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.3
</pre>

### What version of Badger are you using?
1.6 with backports

### Does this issue reproduce with the latest master?
AFAIK, no change has fixed this

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Not applicable for this question

### What did you do?

Wrote millions of keys and values and then deleted all of them

### What did you expect to see?

I would expect there to be some way to remove tombstoned keys that are no longer referenced (especially when the MaxVersions =1 ). I know that this is challenging online due to the way that compaction works, but is there a way to delete the keys if I Flatten the LSM tree offline? I thought that Backup/Restore may fix the issue, but that was unsuccessful as well

### What did you see instead?

Unbounded disk and SST growth based on the number of unique keys written

**Comment by connorgorman** [comment]
@jarifibrahim @manishrjain Sanity check, if I have MaxVersions=1, Flatten the LSM into one level and then stream out the keys. I can safely ignore the ones that are tombstoned because there will only be one version of the key in the LSM correct?

**Comment by jarifibrahim** [comment]
>@jarifibrahim @manishrjain Sanity check, if I have MaxVersions=1, Flatten the LSM into one level and then stream out the keys. I can safely ignore the ones that are tombstoned because there will only be one version of the key in the LSM correct?

@connorgorman How about using the stream framework to stream out the keys. You can ignore all versions after the first one. That should give you unique versions. You can set the key to list function in stream framework to just use the first version it receives.
https://github.com/dgraph-io/badger/blob/1b0c0742acd3b9d0db8e55e1fb6768ea07909069/stream.go#L58-L67

>I would expect there to be some way to remove tombstoned keys that are no longer referenced (especially when the MaxVersions =1 ). I know that this is challenging online due to the way that compaction works, but is there a way to delete the keys if I Flatten the LSM tree offline?

Flatten wouldn't remove the old keys because it only brings all the tables to the same level. Compaction, however, will remove those keys eventually. 
https://github.com/dgraph-io/badger/blob/1b0c0742acd3b9d0db8e55e1fb6768ea07909069/levels.go#L559-L584

**Comment by jarifibrahim** [comment]
Hey @connorgorman, we've made some changes in https://github.com/dgraph-io/badger/pull/1166 which would drop invalid keys sooner now. Please try it out.

I'm closing this issue because I don't think there's anything to be done here. Feel free to reopen.
