### ISSUE TITLE
question wrt transactions and consistency semantics for string interning use case

### ISSUE THREAD

**Issue by Dieterbe** [dgraph-io/badger#1224]
Hello,
I'm looking to use badger as a way to reduce the memory footprint of a program
(https://github.com/grafana/carbon-relay-ng)
This program deals with many objects that have a string key (graphite metrics), typically sized between 50 and 100 Bytes. These keys are typically referenced live a handful of times or more, compounding the space needed.(just the pointer alone is 8B on 64bit) and putting strain on the GC. 

Potentially millions of keys can be live at any point in time, and as time moves on certain keys may become no longer used, whereas new ones may appear.

I'ld like to not keep all these keys in memory, but rather represent them as uint32's internally.
This means I would use badger for both string->ID and ID->string lookups.
(For this use case, disk space usage does not seem like a big concern, and badger can remove stale entries in whichever way is the most efficient. i'm happy to set extra long TTL's or whatever helps here)

The main thing I'm seeking clarification on:
* I don't care for aggressively syncing updates to disk. Data does not need to be persistent - in fact, upon process restart we may as well start with a fresh database.
* I do require that as soon as I set a key=value in my process, that key-value lookup immediately works correctly elsewhere in the program

So in memory I want strong consistency, but not in the persisted data. But I don't want to run the database in memory because the whole point is to save RAM.

It looks like if i want strong consistency in memory, I need to commit transactions aggressively, slowing down the app. Is this correct?

Also, is badger even suitable for what I'm looking to do?
thanks!
Dieter

**Comment by jarifibrahim** [comment]
Hey @Dieterbe , If you need strong consistency, you will have to commit very often. Your reads from other transactions would succeed once the commit completes. 

You can set the `opt.SyncWrites=false` to reduce the time taken by `txn.Commit`. Commits aren't super expensive but if you create a new transaction for every and commit it, it will definitely be slower. You might want to consider writing multiple keys in a single transaction to reduce the cost of commit.

You can also set a long TTL so that compaction can easily drop the keys. Usually, one version of every key is kept in badger.

Badger has a purely `In-Memory` mode but I think it won't be useful for you since you have limitation so on the memory.

>I do require that as soon as I set a key=value in my process, that key-value lookup immediately works correctly elsewhere in the program

This sounds more like a use case for a cache.  How about using https://github.com/dgraph-io/ristretto since you don't need all the crash-resilience/transactional capabilities of Badger?

**Comment by Dieterbe** [comment]
ok, i will think about ways to amortize the commit cost. maybe with wip-batches in memory.

ristretto is purely in-memory, no?

**Comment by jarifibrahim** [comment]
>ristretto is purely in-memory, no?

@Dieterbe Ristretto won't work for you. Ristretto will drop cached data if it doesn't have enough space to store it. And yes, Ristretto is in-memory.

I suggest you try using WriteBatch which should be fast enough to load your data. You can also try having an in-memory batch (using a map?) from which you can read data while write batch is in progress. But if write batch is fast enough for you, this in-memory batch would be unnecessary. 

Please try out WriteBatch and let me how it goes :)
