### ISSUE TITLE
question database replace like redis swapdb

### ISSUE THREAD

**Issue by mschneider82** [dgraph-io/badger#1231]
Hi,

i have a usecase where i get a big database snapshot as json and want to stream store it into badger so i can get values quickly from memory&disk.

How is the best way to update the badgerdb with a new database json snapshot in background?

start transaction
dropdb
insert
commit?

Will the reads still work in background or is a readlock needed?
Or is it better to use a prefix and dropprefix?

**Comment by jarifibrahim** [comment]
Hey @mschneider82, you can use `badger.WriteBatch` API to bulk load the data. You can do a `DropAll` followed by a `badger.WriteBatch` call.

If you need reads to work instantly after insertion, use a `transaction` and commit it often. The `commit` call would block until the `key` is actually inserted in the `LSM Tree` and can be read after the commit completes. If you're okay with some delay in your reads, use `badger.WriteBatch`. `WriteBatch` is much faster for loading data.

`DropAll` is an expensive operation because badger has to `Clean up` all the levels in the LSM tree. You can just close badger, delete the badger directory and start fresh badger instance with your `write batch`. But this would mean the process running badger has to be stopped first.

**Comment by mschneider82** [comment]
Ok thanks

so the best strategy would be to create two badger directories and keep one directory clean for a new writebatch, and switch the db Client between the dirs once the `WriteBatch` with new data is written, and then `Close` the old client and delete the dir

**Comment by jarifibrahim** [comment]
Yes. That should work. If your data (key-value) are sorted by keys, you can also try to use `stream writer` to bulk insert data. Here's a test which shows how to use it
https://github.com/dgraph-io/badger/blob/617ed7c7db9d618b6511adfff5d22dcde2233049/stream_writer_test.go#L57-L64

Please note that stream writer would require data in sorted order and in case you have duplicate keys, you'll have to assign them versions manually (look at pb.KV struct in the test). `Stream Writer` should be faster than `WriteBatch` because the data will be written directly to the Tables compared to writing key-values in an in-memory LinkedList and then flushing it to tables in `write Batch` mode.
