### ISSUE TITLE
Seeking in the reverse direction gives the first result

### ISSUE THREAD

**Issue by celrenheit** [dgraph-io/badger#129]
Hello,

Seeking in the reverse direction should return the last key for a given prefix. However the following example gives me wrong results:

```go
func main() {
	opt := badger.DefaultOptions
	opt.Dir = "mydb"
	opt.ValueDir = "mydb"
	opt.SyncWrites = true
	db, err := badger.NewKV(&opt)
	if err != nil {
		panic(err)
	}

	db.Set([]byte("aaaaaa/1"), []byte("aaa"))
	db.Set([]byte("my_key/1"), []byte("1"))
	db.Set([]byte("my_key/2"), []byte("2"))
	db.Set([]byte("my_key/3"), []byte("3"))
	db.Set([]byte("my_key/4"), []byte("4"))
	db.Set([]byte("zzzzzz/1"), []byte("1"))

	opts := badger.DefaultIteratorOptions
	opts.Reverse = true
	it := db.NewIterator(opts)

	it.Seek([]byte("my_key"))
	if !it.Valid() { // should be valid
		panic("not valid")
	}

	// should be my_key/4
	fmt.Println(string(it.Item().Key()))
}
```

The result should be `my_key/4`  but I either get `it.Valid() == false` or `aaaaa/1`. 
In the forward direction, I get the right result: `my_key_1`.
Is this the intended behavior ?

**Comment by manishrjain** [comment]
In the reverse direction, even `Seek` is reversed. So, if you need to get `my_key/4`, you should be seeking for `my_key~`, so that you'll get the first `my_key<something>` key when seeking in reverse direction.

It mentions this in documentation: https://github.com/dgraph-io/badger/blob/master/iterator.go#L213-L215

I think it's working as expected. Let me know if you want to see something else happen.
