### ISSUE TITLE
Interruptable garbage collection

### ISSUE THREAD

**Issue by Stebalien** [dgraph-io/badger#1324]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 amd64/linux
</pre>

### What operating system are you using?

Linux

### What version of Badger are you using?

v1.6.1

### Description

`RunValueLogGC` cannot be interrupted and can potentially run for minutes on a large enough datastore. This can be a problem if garbage collection is running on shutdown.

It would be nice to be able to pass a context to `RunValueLogGC` to cancel the process early. Alternatively, allowing a concurrent call to `Close` to interrupt a GC run would fix this. However, at the moment, close can't be called concurrently with anything else.

Would a new `RunValueLogGCWithContext` function be considered if a patch were proposed?

**Comment by jarifibrahim** [comment]
This looks like a useful enhancement since GC could take minutes at times to complete.The GC has two steps. The first sampling step can be exited at any time.
https://github.com/dgraph-io/badger/blob/536fed1846d0f4db9579bcff6797614e134eadfa/value.go#L1628 The second step is where we rewrite the value log file. I'm wondering if there would be any side effects of stopping the rewrite while it's running https://github.com/dgraph-io/badger/blob/536fed1846d0f4db9579bcff6797614e134eadfa/value.go#L499

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8734). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
