### ISSUE TITLE
Method to check for existence of key

### ISSUE THREAD

**Issue by whyrusleeping** [dgraph-io/badger#1332]
It would be helpful if we could have a way to check for the existence of a given key without fetching it, currently, we spin up a new transaction and call txn.Get for this, but thats suboptimal. It seems like adding a simple method for this that skips a lot of things just to quickly and efficiently check the thing shouldnt be too hard.

Can someone implement this? Or point me in the right direction to do so myself?

**Comment by jarifibrahim** [comment]
@whyrusleeping how about doing a readonly transaction and then using an iterator with `iteratorOptions.PrefetchValue=false`? This might be faster in some cases than doing a `txn.Get(..)` because `Txn.Get()` will fetch the key and value.

If we were to add a new `db.ContainsKey(...)` function, it would be very similar to the `txn.Get`.
Badger stores data on multiple levels. To check if a key exists in a level, we will need some code similar this
https://github.com/dgraph-io/badger/blob/ef28ef36b5923f12ffe3a1702bdfa6b479db6637/level_handler.go#L259-L287
The code above is for the `Get` operation on a level. The level handler will fetch all the tables that could possibly contain it and then search for the key amongst them.

The check for `key is missing` would be very simple because we have bloomfilters in each table to help with that. 

I am not very confident that if we were to implement the new `db.ContainsKey` it would be faster than `txn.Get`. There might be some improvement, but we'll need benchmarks to verify that.

@whyrusleeping if you can get a cpu profile of txn.Get, maybe we can find opportunities to improve txn.Get.

**Comment by sebheitzmann** [comment]
I am interrested too for a  KeyExist method.
