### ISSUE TITLE
Question: Is Badger a good choice for my use case?

### ISSUE THREAD

**Issue by lolin9** [dgraph-io/badger#1356]
I apologize for creating a GitHub issue for this but I just discovered Badger and Bolt and wanted to ask the authors themselves whether Badger can be a good choice for my case or not. I have an application with these characteristics:

* CLI and used primarily over Linux, Mac, Windows, and preferably mobile environments if possible
* My keys will not usually grow beyond a few hundreds of items and each key generally has a few Kilobytes of values
* The access is mostly reads i.e. writes are rare. (writes are mostly about state and config changes of the application on user interaction)
* Stability is key here, I don't want users to be unable to access their configs a year from now because of some update
* Memory usage should be acceptable for a CLI. Like I said the entire data isn't big at all and should fit, if written as a serialized JSON, into a few megabytes of a file.

As you may have concluded, I just want a K/V store  that acts as a SQLite alternative for a CLI application without having to deal with the SQL weirdness for CLI apps like having to do migrations.

Is Badger a better solution for my case than Bolt and SQLite? Personally I find Badger more featureful (TTLs, encryption), but I fear it's for intensive server applications and microservices not for a CLI.

**Comment by jarifibrahim** [comment]
Hey @lolin9, this is a great question. Let me try to answer it bit by bit
>CLI and used primarily over Linux, Mac, Windows, and preferably mobile environments if possible

Badger should work fine. Would this cli serve a lot of data? If so, you would have to account for the time it might take badger to open your data directory.

>My keys will not usually grow beyond a few hundreds of items and each key generally has a few Kilobytes of values

Badger has an LSM only mode which would be very useful in this case.

>Stability is key here, I don't want users to be unable to access their configs a year from now because of some update

For badger, we support last two major versions (currently it's 1.x and 2.x). A major version update happens only when there are incompatible data format changes. I don't think there will be a major update soon. If you start with Badger v2, you should be fine.

>Memory usage should be acceptable for a CLI. Like I said the entire data isn't big at all and should fit, if written as a serialized JSON, into a few megabytes of a file.

Badger by default isn't very memory friendly. It was built for performance. Since the amount of data you'll store is very less, we should be able to cap the memory to a certain limit. I can help you with some combination of options that would reduce the memory usage. 

>Is Badger a better solution for my case than Bolt and SQLite? Personally I find Badger more featureful (TTLs, encryption), but I fear it's for intensive server applications and microservices not for a CLI.

Badger was definitely built for intensive usage but that doesn't mean a cli cannot use it.

There's one important difference you should be aware of. Badger uses LSM Trees to store data and Bolt uses B+ trees. Theoretically, B+ trees are known to perform better on read workloads while LSM Trees are known to perform better on write workloads. This is subjective to the workload as well. If performance is critical, I will suggest you run benchmarks before making a choice.

Another key difference is that Bolt contains only a single file and no write-ahead log. This means you'd generate less data on disk. Badger, on the other hand, will create 4 files even for 1 byte of data. Badger uses `write-ahead log` file (vlog). This file has to be garbage collected often since it grows every time a write/update is performed. This garbage collection is an expensive operation and might not be cli friendly.

>Is Badger a better solution for my case than Bolt and SQLite? Personally I find Badger more featureful (TTLs, encryption), but I fear it's for intensive server applications and microservices not for a CLI.

Badger does support these features but does your application need it? If not, Badger could be an overkill.

I do not know about the internals of SQLite but since it has been around for a while, it might be the best choice for your application considering its stability. CLIs are installed once and you would want to reduce the number of bugs. Using SQLite would mean you don't need frequent updates to your CLI because of the key-value store was updated. Badger on the other hand is actively being developed. We keep improving things and we try do to frequent updates to badger which would mean your CLI would also need those updates and you would need to do a new release.

Bolt is not being developed as I see here https://github.com/boltdb/bolt so that shouldn't be considered if stability is important.

I hope the answer was helpful to you.
