### ISSUE TITLE
In-memory mode creates physical tables (in the current directory)

### ISSUE THREAD

**Issue by damz** [dgraph-io/badger#1374]
It looks like the in-memory mode creates physical tables in the current directory. This is because `*DB.handleFlushTask` does not seem to have a special case for the in-memory mode.

### Steps to Reproduce the issue

- Run `go test .` and watch SST files being created and destroyed in the current directory.

**Comment by itsyashkothari** [comment]
Hey @damz

I think this is happening because there isn't any check handling the case when InMemory is true but KeepL0InMemory is false. This causes badger to flush L0 on disks. This scenario is happening here.
https://github.com/dgraph-io/badger/blob/dd332b04e6e7fe06e4f213e16025128b1989c491/levels_test.go#L772-L779

@ashish-goswami, is this intended?

I guess there are two ways to handle it
1. return Error while opening db if we encounter this case
2. force KeepL0InMemory to be true when InMemory is true.

**Comment by damz** [comment]
Indeed, the easiest fix would be to make this check `db.opt.InMemory || db.opt.KeepL0InMemory`:

https://github.com/dgraph-io/badger/blob/dd332b04e6e7fe06e4f213e16025128b1989c491/db.go#L1023-L1029

**Comment by jarifibrahim** [comment]
The code @damz pointed out is the correct place to fix this. This is a low hanging fruit and I'll leave it for new contributors.

Thank you @damz and @itsyashkothari !

**Comment by itsyashkothari** [comment]
Hi @jarifibrahim 

Wouldn't the solution provided result in inconsistency in logic.

For example here 
https://github.com/dgraph-io/badger/blob/dd332b04e6e7fe06e4f213e16025128b1989c491/level_handler.go#L191-L195

As KeepL0InMemory==false but actually L0 is in memory. 
I guess there are two ways to handle it

1. return Error while opening db if we encounter this case
2. force KeepL0InMemory to be true when InMemory is true.

I would love to submit PR for this

**Comment by jarifibrahim** [comment]
Approach 1 would mean the user has to set two options to enable `in-memory` mode. This doesn't seem like a good user experience.

> opt.KeepL0InMemory = opt.KeepL0InMemory || opt.InMemory 

This would result in the least amount of changes. Let's go with this approach.
