### ISSUE TITLE
Add checksum to value log entries to detect corrupted data

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/badger#143]
If the process dies while writing to the value log, then the value log may become corrupt.

Adding a checksum to each entry will allow corrupted data to be detected when replaying the value log.

**Comment by peterstace** [comment]
I looked so see what kind of checksumming MySQL uses (for comparison). The most common storage engine for MySQL is MyISAM. This storage engine allows tables to be 'repaired' (rather than just detecting errors), so they're using something more complicated than just hashing.

For something similar, we could use Reed-Solomon encoding. Go implementation: https://github.com/vivint/infectious

**Comment by srh** [comment]
I should point out (as @janardhan1993 reminded me) that whether or not the value log can get corrupted depends on the file system.  On some, appending is safe (you might get a short write, but no garbage data) but on others (such as ext4-writeback) we'll need checksums.

Here's a simple plan for adding checksums.

Suppose we want to append a sequence of values V_1, ..., V_n to the value log.  Then we can write the following:

V_1, ..., V_n, P, Q, C

where P is the offset of the previous file location known to have been synced to disk, Q is the front offset of V_1, and C is a checksum of [V_1, ..., V_n, P].

Of course there's some form of encoding or discriminating bytes so that while scanning forward (when replaying the log from whatever point badger!head! starts at) we can recognize (P, C).

**Comment by peterstace** [comment]
There's an [interesting paper](https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwib152n5MPVAhXCnJQKHfIaBqIQFggmMAA&url=https%3A%2F%2Fwww.usenix.org%2Fsystem%2Ffiles%2Fconference%2Fosdi14%2Fosdi14-paper-pillai.pdf&usg=AFQjCNG4kJpnjdeGI1BWkGthiwoUmuKDPg) about these sorts of properties of file systems.

For simplicity, I was planning to just put a checksum immediately preceeding each V_i.

**Comment by peterstace** [comment]
I'm going to truncate the value log at the first place where the checksum doesn't match.

**Comment by srh** [comment]
How will you know where to stop looking at checksums?  That's what writing the value P gets you above.

**Comment by peterstace** [comment]
I would always check the checksum -- even on parts of the value log that have already been synced to disk. Is that what you mean?

**Comment by srh** [comment]
Okay, so you're checking them during replay.  As long as !badger!head is *only* updated after a sync() to the value log files then you're in good shape.  

We don't want to use reed-solomon encoding.  We aren't expecting individual bits or bytes to be flipped in the case of a process or machine dying while writing -- huge chunks would be invalid data.  We want the cheapest possible checksum for the CPU to compute.

I don't want to spend time looking into it but my guess  MyISAM's "repair" simply gets the table to some consistent state.  Just like replaying the value log is in some sense a form of repair.  It's a defect of the software that they even expose the notion of table repair to the user -- look at the error codes they show like "Duplicate unique key or constraint" -- they're states which you need to repair only because they're possible by design.

**Comment by peterstace** [comment]
Correct, checking during the replay.

Yeah, @manishrjain discussed the Reed-Solomon encoding on Friday, not really useful for the value log. I'm going to use a simple CRC32 hash (should be very fast).

**Comment by peterstace** [comment]
Fixed in PR #148
