### ISSUE TITLE
Value log GC needs to keep up with writes

### ISSUE THREAD

**Issue by srh** [dgraph-io/badger#173]
Right now the way value log GC runs, it's configured by ValueGCRunInterval.  Using the default value, we GC one value log file every 10 minutes.

This is bad because we could write new value log files more frequently than that.  The result is, on a workload that frequently updates a finite set of keys, we get arbitrary growth in disk usage.

So, value log GC should be done not just on the basis of time but also on the basis of how much writing has happened.

**Comment by manishrjain** [comment]
Setting the interval to one minute would fix this problem. This is a dumb, but simple solution.

**Comment by srh** [comment]
We need to fix this.  Otherwise there will be people who decide to check out the DB, run a workload, run out of disk space despite having a small dataset, and quietly decide to use something else, and we'll never know.

It should be pretty simple to have slightly smarter criteria for which to do a value log GC and also to ask whether we should do one every time we open a new value log file.

**Comment by whyrusleeping** [comment]
It would be great to at least expose the GC method to the user. Being able to call GC on badger when our users run an ipfs gc would be very nice.

**Comment by manishrjain** [comment]
Sounds like a good idea. We can just let the user trigger GC, instead of triggering it ourselves. That way, they can schedule it themselves. If they see the data size closer to the limits, they can call it multiple times; or they can just use a timer to call it on frequent interval; or call it when the load is low. In this case, call it when they call other GCs.

Value log GC is an optional thing, useful but not urgent. So, I'm in favor of just exposing it in a way where users can trigger it themselves.

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/badger/pull/225

FYI: This is a breaking change, @whyrusleeping .

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/badger/commit/935ef5ddf169f2bb3fa1d2a44144e07f1538197c submitted.
