### ISSUE TITLE
Deadlock in tests with race detector.

### ISSUE THREAD

**Issue by gavriva** [dgraph-io/badger#178]
Hi guys!

when I run `go test -race` in badger's directory it hangs periodically.
[output.txt](https://github.com/dgraph-io/badger/files/1245573/output.txt)

**Comment by srh** [comment]
Thank you for the report.  We'll get on this soon.

**Comment by srh** [comment]
Working on this.  I've seen occasional hangs too.

**Comment by srh** [comment]
This was reproduced and it looks like another problem with getting compaction to happen. To reproduce I had to add artificial load to my machine by making a few busy-waiting processes (or just run Slack in one browser tab).

**Comment by srh** [comment]
I got it to trigger with some helpful printfs.

In addLevel0Table at the place where we sleep 10ms, we see

Level 0 totalSize: 48201, level 1 totalSize: 125040, level 1 maxTotalSize 131072

At the same time, pickCompactLevels returns an empty slice.  And there are zero active compactions, and in pickCompactLevels `s.cstatus.overlapsWith(0, infRange)` is observed to be false, but also `s.levels[0].numTables() >= s.kv.opt.NumLevelZeroTables` is false, which means we don't have a level 0 compaction.  Level 1 doesn't compact because its size is less than maxTotalSize.

The architectural problem here is that the logic in `addLevel0Table` needs to exactly replicate the logic in `pickCompactLevels` while it sleeps within a loop.  But it's not.

**Comment by srh** [comment]
A fix is implemented in sam/178; I'll let it run a bit before submitting a PR.

**Comment by manishrjain** [comment]
So, Level 0 is below the max size allowed (256MB), also level 0 tablets are less than NumLevelZeroTables. Similarly, level 1 is below its size as well, and that leads to no compactions running. So, what's the issue here?

**Comment by srh** [comment]
addLevel0Table wouldn't progress unless level 0 was completely empty (`s.levels[0].getTotalSize() == 0`), under the assumption that sometime between level 0 being emptied and getting another table, that line of code would get to run.

**Comment by manishrjain** [comment]
Nice catch!
