### ISSUE TITLE
Revisit configurable logging

### ISSUE THREAD

**Issue by kfries** [dgraph-io/badger#1826]
I was reading the comments and was quite disappointed in the solution from a few years back regarding logging.  Just because I don’t want to see info messages, does not mean I don’t want to see warnings and errors.  The problem is that the GO logging that is built in by default so so weak, it is not really ready for true commercial work.  Being able to set the logger to nil throws the baby out with the bath water.  Has there been any attempt to revisit this solution, to use logrus or zap?  Especially with a database, logging is so important for it to be this badly implemented

**Comment by matthewmcneely** [comment]
@kfries Not sure about the 'comments' you're referring to, but are you asking for a logging level option? That seems like a pretty quick fix.

**Comment by matthewmcneely** [comment]
Taking this a bit further, suppose we had a [logr.Logger](https://github.com/go-logr/logr/blob/a49c9717d660988d99b6f931e67c49745caacbcd/logr.go#L239) field in the `badger.Options` struct. You could construct a logr-based [logrusr](https://github.com/bombsimon/logrusr) sink and set that in the Options.

Internally, badger would follow the logging principles set forth in the logr package (the [README](https://github.com/go-logr/logr) there is really a great read). Instead of formatted output (i.e., .Infof()), we'd emit key value pairs. Likewise, we'd follow the verbosity guidelines there too. So an Info log line would be changed like this:

Before
```golang
db.opt.Infof("Set nextTxnTs to %d", db.orc.nextTxnTs)
```

After
```
db.opt.Logr.V(2).Info("Set nextTxnTs", "ts", db.orc.nextTxnTs)
```

Additionally, you could construct your logr.Logger with a _name_, for instance: `badgerLogr := yourexistingLogger.WithName("badger")` and then set the result in the Options struct.

**Comment by xhs** [comment]
I use logrus with INFO messages disabled like this:
```go
dbOptions := badger.DefaultOptions(config.IndexFileDir).WithLogger(log.StandardLogger()).WithLoggingLevel(badger.ERROR)
```

**Comment by matthewmcneely** [comment]
> I use logrus with INFO messages disabled like this:
> 
> ```go
> dbOptions := badger.DefaultOptions(config.IndexFileDir).WithLogger(log.StandardLogger()).WithLoggingLevel(badger.ERROR)
> ```

That seems like a good option, logrus' StandardLogger implements those format functions. I guess what I'm proposing is moving toward the logging principles put forth by the logr package. @kfries would appreciate your input on this idea.

**Comment by mangalaman93** [comment]
I think this solution should work. I would be against breaking the API for logging, unless this is really needed. I am closing this issue for now but feel free to reopen if we can improve it without breaking the logging API.
