### ISSUE TITLE
stable api timeline?

### ISSUE THREAD

**Issue by whyrusleeping** [dgraph-io/badger#223]
When will the API and disk format be stable? I don't want to start integrating this and recommending people use it if things are changing as often as they are now.

**Comment by whyrusleeping** [comment]
Also, while i'm at it, can you provide a mechanism to migrate between manifest versions?

**Comment by deepakjois** [comment]
We are shooting for a stable release soon. We don’t have a timeline, but we are hoping it will happen in the next few weeks.

We have been doing some pretty extensive bencmarking, and also reconsidering some design decisions. There were a few disruptive changes that happened in the last couple of weeks due to that. We have the leeway to make such changes before the v1.0 release, after which the guarantees will be much stricter.

We will look into a mechanism to migrate between manifest versions, when we actually need to do that. Post the v1.0 release a new release of Badger would ideally just work with your existing datastore.

**Comment by manishrjain** [comment]
Regarding the migration, @srh is working on taking version neutral backups via Badger. Those backups can then be used to migrate data between versions.

**Comment by manishrjain** [comment]
Duplicate of #161
