### ISSUE TITLE
A way to force compact Level 0

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#226]
Accept a bool to force a compaction cycle to compact away level 0, during a call to `KV::Close`. While running Gets, the cost of level 0 is much higher than the test of the levels (because we only pick up one file from the rest, but pick up anywhere from 0 to 10 files from level 0). This would be useful for the various bulk loads we're doing.

See a sample output here, created from Dgraph's bulk loader.

```$ badger_info --dir .                                                               ~/dgraph/p
[Manifest]
MANIFEST            446  2017-09-15T14:35:29+10:00
[Level 0]
000017.sst     52073720  2017-09-15T14:35:17+10:00 0
000022.sst     51354907  2017-09-15T14:35:23+10:00 0
000023.sst     46434874  2017-09-15T14:35:27+10:00 0
000024.sst     25442878  2017-09-15T14:35:29+10:00 0
[Level 1]
000008.sst     69905143  2017-09-15T14:34:33+10:00 1
000019.sst     72701320  2017-09-15T14:35:20+10:00 1
000021.sst     57633564  2017-09-15T14:35:21+10:00 1
[Level 2]
000006.sst     72701343  2017-09-15T14:34:32+10:00 2
000007.sst     72701341  2017-09-15T14:34:33+10:00 2
000009.sst     72701331  2017-09-15T14:34:33+10:00 2
000016.sst     72701342  2017-09-15T14:35:16+10:00 2
000018.sst     72701343  2017-09-15T14:35:19+10:00 2
000020.sst     72701338  2017-09-15T14:35:21+10:00 2
[Value Log]
000000.vlog  1073759382  2017-09-15T14:34:09+10:00
000001.vlog  1073742057  2017-09-15T14:34:47+10:00
000002.vlog  1073741987  2017-09-15T14:35:19+10:00
000003.vlog   318559994  2017-09-15T14:35:29+10:00
[Summary]
Level 0 size: 175306379
Level 1 size: 200240027
Level 2 size: 436208038
Total index size: 811754444
Value log size: 3539803420
Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
```

**Comment by deepakjois** [comment]
When this is done, please remember to unskip [this test][1], which is inconvenient to run without forced compaction.

[1]:https://github.com/dgraph-io/badger/blob/37c2a9033b74d39f1d1c8d60f86b68f433134c78/value_test.go#L495

**Comment by manishrjain** [comment]
In fact, we could do this every time DB is closed automatically. I'll look into this.

**Comment by janardhan1993** [comment]
Implemented in master, We forced compact level zero during db close now

**Comment by arctica** [comment]
Could you please expose a public function to force a full compaction? We have a DB that has grown quite a bit but then activity on it shrank again. Due to the low amount of writes right now, the LSM wont trigger a compaction in a long long time and therefor the value log GC also doesn't seem to want to collect any garbage. Right now the DB has 14 tiny entries but is 1.3GB on disk.

**Comment by arctica** [comment]
@manishrjain that issue talks about an offline tool. Not everyone (actually probably only a tiny minority of users) can take a database and therefor the whole service offline for maintenance that might need to happen regularily. Please consider providing a function to make this happen online and via API. As far as I understand, badger already supports online compaction and I assume the value log GC also should be able to run while the DB is in use. It wouldn't even need to run a full compaction until everything is as small as possible, instead the function could allow for continous compaction in small steps to avoid disruption of service. See it this way: that's what every garbage collector in any programming language also tries to achieve.

Until such functionality is implemented, could it be possible to force LSM compaction to happen frequently by choosing small values in the config?

1. Small MaxTableSize (e.g. 1MiB) + NumLevelZeroTables = 2. The idea being to reduce the size of L0 in order to force compaction. Downside would be a lot of small files for larger dbs.
2. Small LevelOneSize, but I guess data has to go through L0 first so if that's big, a small L1 wont help.

It's not so easy to understand the compaction strategy via the docs and options available, maybe I need to read the references whitepapers. I assume a compaction of L0 only results in flushing data to L1 and only if that reaches its threshold, then it will result in a compaction of L1 to L2 etc. That makes compactions of the final level extremely unlikely if the DB once grew to bigger size and then stays at low write volume. Or does compaction of a level which results in a much much smaller size also trigger it to compact the lower level because it knows that there must be also a lot of garbage at that level? If every table knows after a compaction how many keys in it's keyspace it's pointing at the next level, then I guess it should be possible to precisely calculate how much garbage the next level contains (without random sampling). But even random sampling, similar to what the value GC can do, would maybe make sense for the LSM.

Also wouldn't it make sense to have the table/file size grow with the level?

**Comment by manishrjain** [comment]
From what I gather, you're saying that we should compact a level (in LSM tree) even if it doesn't exceed the level size threshold; so that you can continue to achieve the minimum possible size requirement. Why do you have such a requirement (hard disk is cheap and plentiful)? Do you think an LSM tree based KV store the right solution for you? Maybe a B+ tree-based design would be better suited for your use case.

Level 0 does get compacted when it exceeds the size, or when the DB is closed. We avoid data loss by using the value log as a WAL.
