### ISSUE TITLE
Don't write tombstone keys if compacting to current max

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#228]
We can keep track of the current max level up til which the tables have reached. And if we're compacting to this current max level, then skip writing the tombstone keys. This would help reduce the size of LSM tree.

**Comment by srh** [comment]
Note that in order to do this we'll have to keep track of when the last backup was completed, with state on the Badger side of things, and only skip tombstone keys older than the time of (that is, the max cas counter value associated with) the last completed backup.

**Comment by manishrjain** [comment]
Very good point. Keeping a backup state in Badger is definitely cumbersome, and not worth solving for.

The keys by themselves don't add much size because of prefix diffing. So, given the complexity with backup, this is worth punting. If over a long time, a user realizes that the LSM size can be significantly reduced by discarding all the tombstone keys, they can just do a backup and restore to a new Badger instance.

**Comment by srh** [comment]
I don't think keeping backup state in Badger is too bad because the bare minimum we just store one CAS counter value saying: everything <= this has been backed up.

If we wanted to avoid that the user could supply it and update the value at runtime (in Options and through some means of updating the option) and it wouldn't even get stored inside Badger's files.

**Comment by manishrjain** [comment]
There could be multiple backups being taken, some of them could be the ones that user is still keeping track of, others defunct. This is not something we want to track and modify behavior on.
