### ISSUE TITLE
Questions about benchmark

### ISSUE THREAD

**Issue by selforganized** [dgraph-io/badger#245]
Hi,

A couple of questions about the benchmark https://blog.dgraph.io/post/badger-lmdb-boltdb/

1) Do you have data for random reads per second? Right now only latency is available. Throughput data would be helpful too.

2) For sorted range iteration I don't quite understand how Badger could be faster than LMDB & BoltDB which are B+ tree databases. In a B+ tree all records (both keys and values) are stored in sorted order so there's no need to do N random IOs to gather the values while in Badger's case it *is* necessary to do N random IOs because the values aren't sorted. So why is Badger so much faster there?

**Comment by manishrjain** [comment]
1. We didn't run any throughput numbers for reads.
2. Badger can iterate upon keys in sorted order really quickly -- because keys are kept sorted, and kept in RAM due to the small size of LSM tree. We use this to our benefit by prefetching the values for the next N keys (by default 10), so when the user needs them they're ready. Hence, we're able to use the concurrent aspect of SSDs much better than other KV stores, and are able to outperform them. (Note though that we set GOMAXPROCS to 128 to allow Go to experience the SSD throughput potential).

You can see this log for more details about how we ran things:
https://github.com/dgraph-io/badger-bench/blob/master/BENCH-lmdb-bolt.md

Let me know if you have any other questions.

CC: @deepakjois (who ran the benchmarks)

**Comment by tanaka-de-silva** [comment]
How does Badger perform when the LSM tree size exceeds available RAM?

**Comment by manishrjain** [comment]
Badger doesn't require LSM tree to be kept in RAM. It can be memory mapped as well, or just be read directly off disk. Of course, this would impact read latency. Hard to say by how much, because it just depends upon the system.

Given Badger minimizes the size of LSM tree, we highly recommend keeping it in RAM for performance and keeping value log on local SSD.
