### ISSUE TITLE
renaming values

### ISSUE THREAD

**Issue by whyrusleeping** [dgraph-io/badger#325]
Is it possible to efficiently rename values? My usecase is being able to write a bunch of items under a certain namespace, and then process items within that namespace before moving them into a different namespace. Given my current understanding of how badger works, you could put a new entry to the tree that points to the same entry in the value log, then remove the old entry from the tree, which should be quite fast.

**Comment by manishrjain** [comment]
It's a bit more complex than that. The LSM tree entry points to the value log entry. The value log entry contains the original key, value, any meta information, and a checksum. This checksum is a way for us to determine if the log got corrupted due to some system level issues. So, if you change the key, but don't update the key and the checksum on the value log, this could cause strange issues.

There are also other issues like a write not being persisted on the value log, could cause that write to disappear on a crash. Hence, every write is first written to the value log. If that's done anyway, then there's not much benefit avoiding writing the value.

Our current approach ensures safety from system level issues -- so just write a new key-value, delete the other one and later the older value in the log would get GCed.
