### ISSUE TITLE
Refactor runBadgerTest function to be smarter when dealing with options

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger#352]
Here is an example of a recent test that was checked in: 

```Go
	dir, err := ioutil.TempDir("", "badger")
	require.NoError(t, err)
	defer os.RemoveAll(dir)

	opt := getTestOptions(dir)
	opt.ValueLogFileSize = 15 << 20
	runBadgerTest(t, &opt, func(t *testing.T, kv *DB) {
             //…
        }
```

Notice that we need to add the redundant step to create a tmp directory ourselves because `getTestOptions()` needs them. This could be avoided with a minor refactoring. Maybe `runBadgerTest()` could take a func instead of the options themsleves, which will operate on a default set of options and modify them.

**Comment by manishrjain** [comment]
Do make sure that it doesn't take two functions. Func as args makes the
code look ugly.

Sent from Nexus 6P

On Dec 12, 2017 10:49 AM, "Deepak Jois" <notifications@github.com> wrote:

Here is an example of a recent test that was checked in:

	dir, err := ioutil.TempDir("", "badger")
	require.NoError(t, err)
	defer os.RemoveAll(dir)

	opt := getTestOptions(dir)
	opt.ValueLogFileSize = 15 << 20
	runBadgerTest(t, &opt, func(t *testing.T, kv *DB) {
             //…
        }

Notice that we need to add the redundant step to create a tmp directory
ourselves because getTestOptions() needs them. This could be avoided with a
minor refactoring. Maybe runBadgerTest() could take a func instead of the
options themsleves, which will operate on a default set of options and
modify them.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dgraph-io/badger/issues/352>, or mute the thread
