### ISSUE TITLE
Question: what is fastest way to load a lot of keys.

### ISSUE THREAD

**Issue by dvsekhvalnov** [dgraph-io/badger#358]
Hi all, 

this is more question than an issue. Wondering what is fastest way to fetch a lot of keys.

Here is scenario:

1. we do have N keys (10K - 1Mln). And it's not range scan, keys are not 'co-located' if you will.
2. would like to load values for all of them as fast as possible.

What is recommended way? Just do `Txn.Get(..)` one by one in single transaction? Faster way?

Thank you.

**Comment by peterstace** [comment]
Yes, that's the best way to do it.

**Comment by deepakjois** [comment]
@dvsekhvalnov You can look at the data population code in the [badger-bench] repo to get an idea of what you can do.

[badger-bench]: https://github.com/dgraph-io/badger-bench/blob/master/populate/main.go#L69

**Comment by dvsekhvalnov** [comment]
Thanks guys !

**Comment by manishrjain** [comment]
Hey @dvsekhvalnov : Do these following things:

- Set GOMAXPROCS to 128, to allow Go to realize SSD IOPS.
- Run 256 or more goroutines, each running a transaction (concurrently).
- Each txn can run one or multiple Gets serially.

The thing about achieving high read throughput is being able to parallelize the read operations, because that's what SSDs are designed to do -- run high concurrent IOPS.

**Comment by dvsekhvalnov** [comment]
@manishrjain ,

basically:
 1. split our key set into chunks 
 2. fetch chunks in parallel (single transaction per chunk)

?

**Comment by manishrjain** [comment]
Yeah, that sounds good. Parallelize as much as you can. Remember to set GOMAXPROCS too.

**Comment by dvsekhvalnov** [comment]
Thanks for idea !
