### ISSUE TITLE
Version constant?

### ISSUE THREAD

**Issue by mperham** [dgraph-io/badger#385]
You have a changelog with versions in it but no way to determine at runtime what version of Badger is in use.  Perhaps you could add a constant like `badger.Version = "1.3.0"`?

**Comment by deepakjois** [comment]
I think it might be better to expose the manifest version, instead of the Badger version. For all the potential uses a publicly available version that I can think of, a manifest version is more robust and will change less often. Badger minor and patch versions could change due to features being added etc.

**Comment by mperham** [comment]
It looks like you properly tag your releases so I will just pin to a tag, e.g. "v1.3.0", and include that tag in the build.
