### ISSUE TITLE
Surprising performance

### ISSUE THREAD

**Issue by ivanjaros** [dgraph-io/badger#396]
Hi,
I was looking for fast storage in Go and so my first try was BoltDB. I need a lot of single-write transactions. Bolt was able to do about 240 rq/s.

I just tested Badger and I got a crazy 10k rq/s. I am just baffled. I even tried to set the TableLoadingMode and ValueLogLoadingMode options to FileIO, with SyncWrites being true by default(I'm using the DefaultOptions) but the results are almost the same, the only difference was smaller log file(2gb vs few kb/mb based on writes) and tiny decrease in performance.

So I wonder where this performance comes from? I am no DB expert but I would not think that B+tree vs LSMtree would make that much difference. And I do not believe Badger stores data only in memory, so the ACID is there.

What am I missing?

**Comment by pawanrawal** [comment]
LSM tree has an advantage compared to B+ tree when it comes to writes. Also, values are stored separately in value log files so writes are much faster. You can read more about the design here https://blog.dgraph.io/post/badger/.

**Comment by manishrjain** [comment]
We also run transactions concurrently, while BoltDB runs them one at a time. We also ran some read benchmarks against Bolt, and we're neck to neck in terms of reading performance as well, despite B+ trees having an advantage over LSM trees. This is because of our unique design. I'm planning to write a paper on it.

https://blog.dgraph.io/post/badger-lmdb-boltdb/
