### ISSUE TITLE
Write skew anomaly with concurrent transactions

### ISSUE THREAD

**Issue by Preetam** [dgraph-io/badger#409]
Following up from https://twitter.com/manishrjain/status/956501292523769856.

See second paragraph here: https://en.wikipedia.org/wiki/Snapshot_isolation#Definition

Example program: https://gist.github.com/Preetam/5b7f75e0cdff36898aa0d1fade227726

The initial set of keys is "0", "2", "4". Then two transactions are started concurrently.

* Txn A adds "6" to the set and counts the number of odd numbers it saw. It writes that count to "_odd"
* Txn B adds "1" to the set and counts the number of even numbers it saw. It writes that count to "_even"

Those are both committed without conflict.

```
2018/01/25 22:16:19 Total (evens, odds) = (4, 1) doesn't match (_even, _odd) = (3, 0)
exit status 1
```

**Comment by MoZhonghua** [comment]
Even run txn one by one, You can never get (_even, _odd) = (4, 1) :
- A before B: (_even, _odd) = (4, 0)
- B before A: (_even, _odd) = (3, 1)

Anyway, (_even, _odd) = (3, 0) is wrong answer.

**Comment by Preetam** [comment]
Ah, yes. You're right. Good point.

**Comment by MoZhonghua** [comment]
According to [Serializable Isolation for Snapshot Databases](https://courses.cs.washington.edu/courses/cse444/08au/544M/READING-LIST/fekete-sigmod2008.pdf), section 2.3:
```
Phantoms
Throughout the discussion so far, we have followed typical concurrency 
control theory and assumed that a transaction is a sequence of reads and 
writes on named data items. In general, a relational database engine 
must also deal with predicate operations (such as SQL “where” clauses).  
These mean that a concurrency control algorithm must also consider 
phantoms, where an item created or deleted in one transaction would 
change the result of a predicate operation in a concurrent transaction 
if the two transactions executed serially. The solution used in 
traditional two-phase locking is multigranularity locking, where a 
predicate operation takes intention locks on larger units, such as pages 
or tables, to prevent insertion of records that might match the 
predicate.
```

When you iterate the keys, you are running a predicate on whole database, so this should be a read/write confliction if other txn make __ANY__ changes to database. 

In relational database, there is a table to lock. In badger, only whole database to lock.

So the simplest solution is mark txn as READ_WHOLE_DB when it creates an iterator,  abort this txn if any other txn write changes to database and commit bofere it . But this will cause a long run iteration txn to abort too easily, and very inefficient.

**Comment by manishrjain** [comment]
You have raised a valid issue.

Let's start with understanding the current behavior. Your read set is [0, 2, 4]. The write set is [6, _odd] and [1, _even]. There're no conflicts here, which is why both succeed and produce the (3, 0) result. It makes sense if you consider these keys as a disjoint set.

However, the interpretation here is that the read set is a range between [0, inf). Only in that interpretation, there would be conflicts between the two txns. Now the question is, how do you indicate this interpretation?

Deducing a range of keys based on an iteration would still have this issue, because 6 would be considered outside the scope for iteration which went from [0, 4]. So, the user would have to specify what the intended range is, for conflict detection to work. This would be better than considering the entire DB as one big lock.

Thoughts?

**Comment by MoZhonghua** [comment]
A new setIntentRange()-like API seems OK to me,  or maybe user can register a predicate function like this:

```go
type PredicateFunc func(key []byte) bool
```
This predicate should return true if the key in user's intended range and return false otherwise.

When commit, badger run all registerred predicate function against keys that may arise rw confliction. This should give more user options to specify intended keys than a simple range.

**Comment by manishrjain** [comment]
Doing this check against all written keys across the DB wouldn't be efficient. This is specific to iteration, and I think should only be part of the Iterator API (not the Transaction API as I mentioned earlier).

Something along the lines of: `Iterator::SetLockRange(startKey, endKey []byte)`

**Comment by MoZhonghua** [comment]
I can't see any way to ensure this confliction check without checking against all spurious written keys if we don't bother writer to aslo hint badger about this LockRange.

For example, two txn runs concurrently, and txn A has written some keys, and then txn B create
an iterator with terator::SetLockRange(startKey, endKey []byte), how can we ensure keys written by txn A is not inside this LockRange?

Anothor thought: 
This write skew should be rare in pratical use, because normally user will write some overlapped data.  How about just keep current behavior, and add a new flag in options to let user require full SSI. When this flag is on, we add a READ_ALL flag to txn when user create an iterator in a writable txn.

**Comment by funny-falcon** [comment]
This is well known fact: serializable transaction have to deal with predicates in the (almost) same way as with rows

> For example, two txn runs concurrently, and txn A has written some keys, and then txn B create
an iterator with terator::SetLockRange(startKey, endKey []byte), how can we ensure keys written by txn A is not inside this LockRange?

When B meets invisible row, inserted by A, it remembers R-W antidependency on A. When B commits, it checks if A has also R-W antidependency. If A has no antidependency, then SSI theory proves there is no transaction conflicts. If A has any antidependency, then SSI tells that conflict is possible, and one of these transactions have to be aborted: either A or B.

If A sees predicate lock (holded by B) covering row A tries to insert, it informs B to remember r-w antidependency.

It is the very same with handling rows:
- if B reads old version of row, that has newer (but invisible) version created by A, then B remembers r-w antidepency on A.
- if A updates/deletes row, already read by uncommitted (at the A's start) transaction B, A registers in B r-w antidependency on A.
- when B commits, it checks if A has any r-w antidependency, or not. If A has, then it is called "dangerous structure" by SSI, and one of A or B have to be aborted. If A has no any r-w antidependency, conflict is impossible, so both A and B may be committed.

(Note: if B commits before A, then A have to know that B has r-w antidepency on A. Then if A has any r-w antidepenency at the time A commits, A have to be aborted, because B is already committed).

(Note: I tell "B has r-w antidepenency on A" if there is "A->B r-w antidependency" , that means B have to be committed before A in total order. I don't if I tell "B has r-w antidepenecy on A" correctly, or it should be spelled in opposite way "A has r-w antidependency on B").

Reading article https://blog.dgraph.io/post/badger-txn/ I don't understand: do you really implements SSI, or just Optimistic Concurrency Control? OOC also can provide serializable transaction isolation level. But it is not SSI.

Two classic papers on SSI are : [Serializable Isolation for Snapshot Databases](https://courses.cs.washington.edu/courses/cse444/08au/544M/READING-LIST/fekete-sigmod2008.pdf) and [Serializable Snapshot Isolation in PostgreSQL](https://arxiv.org/pdf/1208.4179.pdf) .
Quote from the second:

> Note that the definitions above referred to objects. We use this
more abstract term rather than “tuple” or “row” because dependencies
can also be caused by predicate reads. For example, if T1 scans a
table for all rows where x = 1, and T2 subsequently inserts a new row
matching that predicate, then there is a T1→T2 rw-antidependency.

**Comment by msackman** [comment]
IMHO, the intent of an iterator is to iterate over the entire database, regardless of the content. So your readset is the database, not the content. This is the expected, correct, and intuitive behaviour. Anything else will lead to a more complex and less friendly API, or surprising behaviour, or both.
I'd be surprised if benchmarks really show that locking the database has a crippling impact on performance. Don't forget that this sort of issue **can't** happen in LMDB because that uses a single writer, so all updates are linearly serialized, and it's still hardly slow.
I strongly believe correctness, intuitive behaviour, and simple predictable APIs should always take priority over performance.

**Comment by campoy** [comment]
Hey @manishrjain, could you give an update on the status of this issue?
It seems it's been stale for quite a while so I wonder if we should close it or plan for a fix.
