### ISSUE TITLE
Can't get value if it will be greater than 31 bytes

### ISSUE THREAD

**Issue by hofstaetter** [dgraph-io/badger#484]
I have following simple code:

package main

import (
	"github.com/dgraph-io/badger"
	"log"
)

type Drive struct {
	database badger.DB
}

func NewDrive(dir string) Drive {
	d := Drive{}

	opts := badger.DefaultOptions
	opts.Dir = dir
	opts.ValueDir = dir
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal("[Drive::new]: %v", err)
	}

	d.database = *db

	/* prepare database */
	err = d.database.Update(func(txn *badger.Txn) error {
		txn.Set([]byte("root"), []byte("aaaaaaaaaabbbbbbbbbbccccccccccdd"))

		return nil
	})
	if err != nil {
		log.Fatal(err)
	}

	return d
}

func (d Drive) get(id string) {
	err := d.database.View(func(txn *badger.Txn) error {
		i, err := txn.Get([]byte(id));
		if err != nil {
			log.Fatal(err)
		}

		v, err := i.Value()
		if err != nil {
			log.Fatal(err)
		}

		log.Print(v)

		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
}

and my main methode looks like this:

d := NewDrive("/tmp/test")
d.get("root")

If the value in my constructor ("aaaa...ccdd")is longer than 31 chars i get following error:
`Invalid value pointer offset: 107 greater than current offset: 107`
When i change the value to "aaaa...ccd", which has less or equal than 31 chars, everything run fine.

Can someone help?

Best regards

**Comment by schomatis** [comment]
@hofstaetter  You are making a copy of the DB control structure and some rather strange things are happening.

```
d.database = *db
```

You should always handle the DB through the pointer returned by `Open()` instead of handling its value through the `*` operator.

So your `Drive` structure would look like this:

```
type Drive struct {
  database *badger.DB
}
```

and then you could make the copy of the pointer (not the value) of the DB:

```
d.database = db
```

@manishrjain Maybe this could be documented explaining that `badger.DB` should always be managed through its pointer and not copied, since Go simplifies the handling of pointers to the extreme where the user can call methods with pointer receivers through the value object without any notification.

**Comment by hofstaetter** [comment]
Thank you!
Everything works fine now!

**Comment by manishrjain** [comment]
@schomatis : It would be good to add a couple of sections about proper usage of Badger. Copying keys, using values (or copying them), closing iterators, not using the same key (without copy) across loops, etc. Explaining the scope where a variable would be valid and where not, etc. In that section, we could also mention this particular pointer thing.
