### ISSUE TITLE
Allow a way to call value log sync every N writes

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#526]
Currently, we have a boolean option to do either SyncWrites or not. We could make this a bit more configurable by allowing sync every N writes, where N is specified by the user. This would perform better while also providing more control over the durability guarantees.

**Comment by wvh** [comment]
Another option could be a Flush() function that allows sync by means of a deadline ticker, so time based instead of N-writes based.

**Comment by arctica** [comment]
N-writes based without a timer would mean high chance of data-loss during a crash when there is a low amount of writes.

You usually want a combination of both. Set a min and max for both number of writes and milliseconds. Flush when either of the max conditions or if both min conditions are reached.

Example: min_time=100, max_time=1000, min_writes=10, max_writes=1000

This would mean a flush happens if 1s passed OR 1000 writes happened OR (at least 100ms passed and at least 10 writes happened).

This strategy gives hard upper bounds on the possible dataloss in case of a crash and reduces the number of syncs to a minimum.

Just providing the max settings would also provide pretty good flexibility.

**Comment by campoy** [comment]
Hi there, everyone.

I'm curious about what config mechanisms you'd like to see implemented to configure how often a sync is performed.

I'm thinking that maybe we can improve our current API to add more config options while we work on badger v2.

**Comment by wvh** [comment]
I've been using a ticker to write batches with a deadline, like in this example:
https://blog.gopheracademy.com/advent-2013/day-24-channel-buffering-patterns/#putting-it-together

The desired logic is to write 1 second batches, that is, if a record comes in, a ticker is started to batch any further writes up to one second and everything is then written in one batch operation.

I'm not sure if that sort of functionality is too high-level for including in badger directly, but the proposed "every N writes" in the title would probably also need a deadline ticker to avoid losing up to N - 1 writes if the rate is low and the service crashes or terminates.

**Comment by campoy** [comment]
I think this is something that could implemented on top of badger, by using the `badger.WriteBatch` API added in v2.0.0 (about to be released).

Have a look at this [gist](https://gist.github.com/campoy/a494cb382aeb487063440f99fde55e09) which I hope helps you understand what I mean.
