### ISSUE TITLE
Corrupted badger database - Assert failed

### ISSUE THREAD

**Issue by leerspace** [dgraph-io/badger#541]
While using go-ipfs with a badger database, the database became corrupted at some point and would return this error when trying to start the daemon: `Error: Unable to replay value log: "C:\\Users\\user\\.ipfs\\badgerds\\000088.vlog": Data corruption detected. Value log truncate required to run DB. This would result in data loss.`. Attempting to use `badger backup -t` to truncate the value log now results in an `Assert failed` error.

More details are in ipfs/go-ipfs/issues/5280

**Comment by manishrjain** [comment]
So, I had a deeper look today, and this is what I found.

Issue 1:
There's a value log file 85 missing. It looks to me like it was accidentally deleted because the transaction timestamps in 84 and 86 are wide apart.

```
File: 84

2018/08/13 17:49:17 Found txnTs: 1797168
2018/08/13 17:49:17 Finished txnTs: 1797168
2018/08/13 17:49:17 Found txnTs: 1797169
2018/08/13 17:49:17 Finished txnTs: 1797169
2018/08/13 17:49:17 Found txnTs: 1797170
2018/08/13 17:49:17 Finished txnTs: 1797170
2018/08/13 17:49:17 Found txnTs: 1797171
2018/08/13 17:49:17 Iteration took: 244.124911ms
2018/08/13 17:49:17 Iterating file id: 86
...
2018/08/13 17:49:18 File: 86. Count: 55000.
2018/08/13 17:49:18 lastCommit: 1797171. txnTs: 1898499
```

There's a 100K txn timestamp difference between the two files, which makes me think 85 might have been deleted. Typically, Badger tends to pick up earlier files for GC, but no earlier file has been GCed. So, it weakly indicates that the file got deleted somehow.

Issue 2:
A single transaction is not contained within the boundary of the value log 84. We made this change earlier this year: https://github.com/dgraph-io/badger/commit/b5727f1b8485a1812e3e904216cc01de7346dce5 , so all writes for a single txn would fall within the same value log file. But, txnTs 1797171 starts in 84, but doesn't finish there; so that logic is being violated here. So, either your Badger version is older than Feb 19, 2018 (earlier than v1.4.0), or this contains some modifications to Badger code outside of master.

Issue 3:
For some reason, the last persisted value log head pointer is still zero. So, all the value logs are being replayed -- this takes time. On my rotational HDD, this is taking 18 mins. I see some .sst files on disk, so this looks very strange that the head pointer didn't make it when those files were persisted. Again, something fishy here.

So, this directory is in a weird state, and this is not the typical Badger behavior (looks like external actions are at play). What is the way out? The backup currently iterates over SSTables to do the backup, which has checks and guarantees in place -- but those are being violated here.

Alternatively, I could provide a way to do the backup, which only goes through the value logs; so you can retrieve your data back. Let me know what you think.

**Comment by leerspace** [comment]
I'm pretty sure the version of go-ipfs I was using is using a version of newer than v1.4.0. I can't comment on whether go-ipfs is doing anything non-standard with the badger repo, but I didn't do anything to it outside of attempting to recover it with `badger backup` after getting the `Unable to replay value log` error.

> Alternatively, I could provide a way to do the backup, which only goes through the value logs; so you can retrieve your data back. Let me know what you think.

@manishrjain I'd be interested in a command to recover the data. Thanks for looking at this.

**Comment by manishrjain** [comment]
Unable to determine the actual cause of this issue -- it looks like there might be external factors in play here, but can't be sure. At the very least, it doesn't indicate any specific issues in Badger.

This issue does indicate the need to build a tool which can recover data by only reading the value log. Created an issue here: https://github.com/dgraph-io/badger/issues/551
