### ISSUE TITLE
Documentation for faster reclamation of disk space

### ISSUE THREAD

**Issue by sathyanarayanant** [dgraph-io/badger#542]
It would help if the documentation could be updated to include the badger options required for faster reclamation of disk space after keys are deleted.

**Comment by l0k1verloren** [comment]
I found this looking for some idea what to do when I had a database suddenly balloon in size. The values were very long, and repeatedly updated.

The database should have been 1/5th the size or less than it was. I am testing changing this ValueThreshold up and maybe suggest that it be highlighted for the case of storing large blocks of data.

In my case it was just a simple array of two integers, but many records were getting well over 20kb in size and each read/write this was the amount going in.

I figure the size result is because it was not compacting ever growing logs (growing in length of its unit parts). In my case, it looks like I have to raise that ValueThreshold a lot. The records in question I already know are some of them getting to over 20kb in length. My database is append only. I think that for this type of data input the log explodes in size. Maybe if I delete the key first also?

**Comment by campoy** [comment]
Issue closed after lack of activity.

Please feel free to reopen if your issue/concern is still relevant.
