### ISSUE TITLE
Open slow when 621GB data in badger

### ISSUE THREAD

**Issue by BeaverCC** [dgraph-io/badger#543]
I have a badger db, the size of that db directory is 621GB. I open it with code
```
	path := "/data/d1/data"
	opts := badger.DefaultOptions
	opts.Dir = path
	opts.ValueDir = path
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
```
And it takes 9 minutes. How can I open it faster?

**Comment by manishrjain** [comment]
Can you post the output of `badger info`?

**Comment by BeaverCC** [comment]
The db grows to 5.6T now, and the open time is 14 minutes. 
The output is too long, so I put it [here](https://gist.github.com/BeaverCC/3674f4056e6b6a6ebdd964f05fa24aeb)

**Comment by manishrjain** [comment]
You only have a few SSTables. The problem is probably mmapping all the value log files, that takes time. You could change the option so value log is FileIO, and re-try.

	ValueLogLoadingMode: options.FileIO,

**Comment by BeaverCC** [comment]
I tried that. It takes 5.5 hours this time. And the disk io is almost full.

**Comment by manishrjain** [comment]
I've seen Badger take time when the value head pointer isn't caught up to the tail of the value log. That means, when you open the DB, it has to replay a big chunk of value logs, which is why it is taking time to open. (We could make that step obvious by adding logs.)

You could confirm that by adding some logs around replay, or looking for "Seeking at value pointer"
https://github.com/dgraph-io/badger/blob/341a135a4ab7d861599a45ca4ce00412c690bf66/value.go#L757

in `/debug/events`, if you run `badger backup` tool; and see which file is value log head pointing to. It would need to replay all value log files after that.

**Comment by manishrjain** [comment]
I just pushed a change https://github.com/dgraph-io/badger/commit/3a87f6d9c273c4a5aaf4a69eb82ecfafc8d767d7, so Badger would now log if it is replaying value logs at Open.

Try it out with this change.

**Comment by niemeyer** [comment]
@BeaverCC What did you end up with, out of curiosity?

**Comment by BeaverCC** [comment]
@niemeyer Yes. But this is not the only reason. We did some other tests.

**Comment by niemeyer** [comment]
@BeaverCC Sorry, the question was probably unclear: which alternative did you end up with? Can you share that?

Also, why, if you have the time (and are allowed) to explain it.

**Comment by jojo05** [comment]
+1

**Comment by BeaverCC** [comment]
@niemeyer We decide to use HBase instead. 
Because HBase can store data in as many nodes(servers) as we want, and rebalance data between servers automatically.
