### ISSUE TITLE
Tool to recover data from value log

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#551]
We need a way to replay only the log files in the value log and recover Badger data.

**Comment by mjentsch** [comment]
Badly needed! Even SyncWrites set to true keeps leaving corrupt databases behind when Badger panics. We have 1.6.0 crashing from time to time during compaction and no easy way to upgrade to v2 due to the DB sizes (and no idea if v2 would not crash because of the same weakness). All we can do is removing the complete DB and reshard from the other cluster members.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8718). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
