### ISSUE TITLE
MacOS: possible data loss/corruption

### ISSUE THREAD

**Issue by networkimprov** [dgraph-io/badger#563]
fsync() on MacOS does not sync to disk; the correct sync method on MacOS is via fcntl(). Golang os.File.Sync() doesn't do this in version <= 1.11. A fix is in place for 1.12. golang/go#26650

Replace os.File.Sync calls with a direct syscall as a workaround until Go 1.12. golang/go@be10ad7

**Comment by campoy** [comment]
Thanks for the pointer, I had missed that golang issue!

This should be fixed ASAP on master and make sure that v2 and following version use the correct implementation for Go 1.11 and below.

**Comment by networkimprov** [comment]
Or just panic in MacOS builds for Go <= 1.11 until someone complains :-)

**Comment by networkimprov** [comment]
And what about that bounty? I'm the one who found and filed the issue on the Go repo :-)

**Comment by campoy** [comment]
I'm not sure how bounties work yet, tbh.
I'll let @danielmai clarify what the next step is.

**Comment by danielmai** [comment]
As per the rules of the data-loss challenge, we expect reports to include reproducible instructions that demonstrate data loss with Badger. However, given the specifics of this issue, being specific to macOS, and that this has been fixed in Go 1.12 thanks to your report, I don't see a need for reproducible steps with Badger per-se.

@networkimprov I'll be happy to reward you a partial bounty amount for identifying the issue :1st_place_medal:. Feel free to send me an email (on my GitHub profile) and we can further discuss the bounty details.

**Comment by campoy** [comment]
Working on a work around while complaining on https://github.com/golang/go/issues/26650#issuecomment-502792459.
