### ISSUE TITLE
Issue truncating vlog after crash

### ISSUE THREAD

**Issue by rjasonadams** [dgraph-io/badger#613]
Hello,

We had a server crash and after the crash Badger is having issues truncating vlog files. The error we get is:

`truncate ./Values/002077.vlog: invalid argument`

I've tried a few things to debug. I moved the data to another drive, reformated, used a different filesystem (this is happening on XFS). No luck.

**Comment by manishrjain** [comment]
Arr... shit. This is a bug. Been reported a few times in the wild, but I always thought it's a file system or Go library issue. The error returned is not helpful at all, as this issue filed here says as well (in retrospect, I should have asked the users to try with strace).

https://github.com/golang/go/issues/9640

Ok. The reason it's been difficult to catch is, because if there're multiple log files, then all but the most recent one is opened as read-only. A truncation can happen if an entry's checksum doesn't match, or there are partial writes. This typically happens in the most recent log file (possibly all our tests are like that), and therefore truncation happens fine. However, if we run truncation on other files, which were opened read-only, this error is thrown.

I'll write a test case and verify my hypothesis here.
