### ISSUE TITLE
arm64 environment, Prompt: "function not implemented, Unable to mmap RDWR log file" error!!

### ISSUE THREAD

**Issue by wyblyf** [dgraph-io/badger#721]
Details：
![image](https://user-images.githubusercontent.com/6084318/53283004-703b8f00-377a-11e9-93ff-3e2a6f680b7e.png)
![image](https://user-images.githubusercontent.com/6084318/53283025-ea6c1380-377a-11e9-9870-8d5cd55a31a4.png)

**Comment by wyblyf** [comment]
The latest version test result:
![image](https://user-images.githubusercontent.com/6084318/53283178-53ed2180-377d-11e9-9f99-98f87be092db.png)

**Comment by campoy** [comment]
Hi @wyblyf,

In order to help use reproduce your issue. Could you share a non-image version of your code reproducing the issue?

We'd also like to have more information about what version of the repo you're working with, as well as the platform/arch and any other details you think could help us with the investigation?

Thanks
