### ISSUE TITLE
value log truncate required to run db. this might result in data loss

### ISSUE THREAD

**Issue by qweawdqq** [dgraph-io/badger#744]
value log truncate required to run db. this might result in data loss
Win7 will be prompted
Mac can start normally

**Comment by manishrjain** [comment]
You might need to enable the Truncate option to get past this. Windows has an issue, that I don't recall right now, which causes Badger to require truncation.

**Comment by alinnert** [comment]
@manishrjain shouldn't this at least be documented? The readme doesn't mention the word "truncate" at all. The only options documented are about memory usage.

This happens every time you kill a process that has a badger store still open. I'd say this happens to everyone who starts tinkering around with BadgerDB on Windows. In order to avoid that you need to implement a "graceful shutdown" first, which at least I did only a little later on.

Wouldn't it be an option to enable this option on Windows by default? Or do truncating once a broken store should be opened? Once you're in this situation there are only two choices (I can think of):

1) Enable the Truncate option and risk data loss*
1) Delete the entire store and start from scratch.

*) What data exactly? The data from not closed transactions or something like that (which would be kind of predictable) or more random data across the entire store (because everything got really unstable and hard to recover from)?

Often the second choice is not an option, especially in production. While development it might be okay, though.

**Comment by alinnert** [comment]
Okay, I just stumbled over issue #434. This explains why truncation shouldn't be done automatically.
