### ISSUE TITLE
Missing CASMismatch error when performing concurrent writes

### ISSUE THREAD

**Issue by 1lann** [dgraph-io/badger#77]
Firstly, I love what you guys have made, I think Badger is amazing and I really appreciate the creation of a really fast pure Go key-value store. Thank you so much for it.

**EDIT: Sorry! The first problem is actually documented, my bad! The second problem I had still is unexplained though. I've edited the video link to skip to it.**

So it appears that concurrent reads then a write can sometimes not trigger a CAS mismatch error, I've made a screen capture to demonstrate this: https://youtu.be/iMOskJT--2k?t=3m1s

Here's the program I wrote to demonstrate this: https://gist.github.com/1lann/30cc4c981449fa13db7e8d9943dfc2e6

I also have a question, is there a defined way to use `CompareAndSet` but for non-existent documents? For example if I read a document, and I find that it doesn't exist, so I decide to create it, is there a way to check nothing else created it concurrently in-between me checking it and writing it? Thanks.

If you need it, here is my Go version and environment:
```
# go version
go version go1.8.3 darwin/amd64

# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jason/Workspace/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mj/9h_k_k_1751_7c85z0b2_l0w0000gn/T/go-build899730521=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by manishrjain** [comment]
Thanks for the video, @1lann. That was very helpful in understanding your problem.

So, when you retrieve a value via `Item`, it does things within to avoid unnecessary memory allocation. The value that you receive, is a portion of a bigger slice, which contains all the writes in memory table. So, when you modify what is returned to you directly, which is a pointer to something that's already written, you end up modifying the underlying data as well.

Therefore, all `Value()`s should be copied over first before re-using.

Regarding concurrent writes, I modified the program to do the read before attempting the writes, so that at least one of them would always fail. Turns out there was a bug: We weren't seeding rand, so the same CAS counter was being produced for the new write as the old one. Hence, both writes would run, because after the first write, the CAS counter was unchanged. That is now fixed.

Regarding CAS for non-existent docs, I want to write a `GetOrTouch` method, which would achieve what you want, i.e. create a key only if it exists, and also give back a counter that you can use for further writes. Expect that to happen soon.

**Comment by 1lann** [comment]
Awesome, thanks for the explanation and fix. I'll be looking forward to the new `GetOrTouch` method.

Regarding the CAS counting, does that mean it's possible for there to be a collision where the new CAS is the same as the previous one? Statistically speaking, when generating random 16-bit integers 46,000 times, there is a 50% chance that two random numbers sequentially generated were the same. (`1-((1-(1/65535))^46000) ≈ 0.5`). If this is a potential problem, is there a way to fix it?

Also, thanks for your talk at golang-syd meetup last month, it was the first meetup I attended. Your talk was really informative (and it's where I learnt about Badger!).

Shameless plug: I'm actually using Badger as the underlying key-value store for an embedded Go database I'm developing for fun: https://github.com/1lann/cete. Thanks for making Badger!

**Comment by manishrjain** [comment]
The new CAS has to be the same as the previous one for the same key, also about the same time range, when a client could have read the counter, and then found it again after a few Sets. So, it's pretty rare.

Talk: Thanks! Glad you liked the talk.

Cete: Really nice project! Sounds exciting.

Your video explaining the problems is really nice. I think it would be great if you could make a video explaining how to use Badger. We could host it on our README. Would be great for the community!

**Comment by 1lann** [comment]
Thanks, making a how-to video sounds good! I'll try to make one and I'll link it over to you.

**Comment by 1lann** [comment]
@manishrjain I've taken a shot at making a basic introductory level tutorial, that covers opening a key-value store and making sets/gets to it. Let me know what you think: https://youtu.be/XBKq39caRZ8.

**Comment by manishrjain** [comment]
Beautiful video! Very well done!

Want to send me a PR with mods to Badger README so it's there? Also include a link to your twitter etc., if you'd like.

If you decide to make this a series, we could have a link to the playlist from README.

**Comment by 1lann** [comment]
Awesome, thanks. I've gone ahead and made the PR. I'll make more PRs if I make a video series.
