### ISSUE TITLE
Transaction error on backup restoration

### ISSUE THREAD

**Issue by awishformore** [dgraph-io/badger#820]
We are running badger in a memory-constrained environment of less than 200 MB. When reducing the memory table size too much, the `db.Load(file)` call will fail with `Txn is too big to fit into one request`. I'm assuming this is due to the fact that it tries to squeeze the entire loading into a single transaction, which can not be bigger than the memory table limit? Would it be a good idea to change the code to batch this into several transactions, as no other operations should be executed on the database during loading anyway?

**Comment by ashish-goswami** [comment]
@awishformore This looks like an issue at our end. We will check and get back to you.

**Comment by jarifibrahim** [comment]
The `transaction too big` is being returned because we have hard coded the transaction size to be 1000 entries. The following code should take in to account the size of the tables and calculate the appropriate transaction size
https://github.com/dgraph-io/badger/blob/0ce1d2e26af1ba8b8a72ea864145a3e1e3b382cd/backup.go#L159-L161
