### ISSUE TITLE
keyBuf for bloom filter takes too much memory

### ISSUE THREAD

**Issue by simonxw** [dgraph-io/badger#942]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.12

</pre>

### What version of Badger are you using?
1.5.5

### Does this issue reproduce with the latest master?
no test yet but I guess so

### What did you do?

This is related to the issue #927, with different angles. There was a change about writing keys to keyBuf instead of adding keys to bloom filter directly. From memory consumption point of view this might not be a good idea as obviously the whole idea of bloom filter is to save space. 

i.e. I wonder why we made this change of writing keys to keyBuf?

Thanks,

**Comment by ashish-goswami** [comment]
@simonxw If we have count of keys in advance, bloom filters can be created with desired false positive rate. Thats why we have all the keys in keyBuf. At the end when Finish() is called on table builder, bloom is created and all keys are put into it.
We are working on a solution to have hashes of keys in memory instead of actual keys.

I am closing this issue. Feel free to comment on #927
