### ISSUE TITLE
a benchmark to investigate: CockroachDB external storage use case

### ISSUE THREAD

**Issue by tschottdorf** [dgraph-io/badger#95]
We evaluated badger (mostly for fun) when discussing external storage for CockroachDB, and it didn't go well. There are probably many low-hanging fruit there; apologies for leaving relatively unpolished work here, but I thought it could be a good starting point for making badger more competitive. See

https://github.com/cockroachdb/cockroach/pull/16069#issuecomment-306237860

and

https://github.com/cockroachdb/cockroach/pull/16343 (the branch is still available).

Unfortunately, the standard invocation

`make bench PKG=./pkg/sql/distsqlrun TESTS=TestDiskSorts TESTFLAGS=-v`

already doesn't compare badger against the other options; it was abandoned before that. However, the history of the branch does have a `func sortBadger(t *testing.T, input RowSource, out procOutputHelper)`, so it's probably just a matter of reverting appropriately.

What's implemented too is `(ss *sortAllStrategy) sortBadger(s *sorter)`, though @asubiotto would have to remind us how to actually exercise that code. My understanding is that this bit is best ignored.

I don't think we're going to put any real work into this, but hope it's useful to you in some way.

**Comment by manishrjain** [comment]
Thanks for sharing. I'll dig deeper to see what you tried.

From a cursory look, it looks like you guys ran `Set` one by one in a loop; which is almost never how you'd run it in real world situation. We never tested or optimized Badger for that. In fact, we get asked that so much that I made it part of our README. Batches + goroutines if you want performance (same goes for RocksDB).

It doesn't look like you guys came to the stage of trying random Gets, which is where Badger really shines. Note that Badger uses a different design which is what causes it to outperform RocksDB. We did some pretty extensive benchmarking against RocksDB here:
https://open.dgraph.io/post/badger/
Even with 1KB values, Badger is over 4x faster in terms of loader throughput. What sort of key-value sizes do you see in CockroachDB? It would make sense to load a data set representative of that.

Data loading for smaller values is a bit slow compared to RocksDB, mostly because their compactions are optimized. But, writing a thousand or 100K keys would not even test that, and just hit memory in both the systems. So, a single loop doing Sets is just teasing the design differences (Badger has to write to value log, while RocksDB doesn't).

**Comment by tschottdorf** [comment]
Yep, the lack of batching was pointed out in our discussion as well (though I'd really hoped we had actually tried it; perhaps we hadn't but I thought we did somewhere).

We're aware of the blog post, which is why we tried it in the first place (again, mostly to see what would happen).  I'm curious whether you can beat RocksDB here with a proper setup -- we're not doing random reads in this use case. In fact, the whole point of using an on-disk store here is getting the data sorted without too much hassle, so correspondingly you expect mostly sequential reads once it is.

**Comment by manishrjain** [comment]
So, if I understand the setup: You have millions of keys, with negligible values? And you want to read them back in a sorted order? Can probably build a small test case to test that. Note that the size of the value is going to make a big difference in Badger vs RocksDB performance.

**Comment by ashwin95r** [comment]
Did some quick benchmark on adding ~2.8M keys and then iterating on them: 
https://github.com/dgraph-io/badger-bench/blob/master/rw-bench/bench_test.go

The results are: 
```
=== RUN   TestPutAndIterate
Value size: 1024
Num unique keys: 2855231
rocks iteration time:  1.717578587s
rocks time:  13.540254938s
Num unique keys: 2855231
badger iteration time:  1.231884332s
badger time:  16.91380382s

=== RUN   TestPutAndIterate
Value size: 128
Num unique keys: 2855316
rocks iteration time:  1.641643682s
rocks time:  9.72966573s
Num unique keys: 2855316
badger iteration time:  1.207451184s
badger time:  13.3816506s

=== RUN   TestPutAndIterate
Value size: 0
Num unique keys: 2855279
rocks iteration time:  1.652722679s
rocks time:  8.782233328s
Num unique keys: 2855279
badger iteration time:  2.109307851s
badger time:  15.168629622s
```

**Comment by manishrjain** [comment]
The trend here doesn't look right. Badger goes from 15 -> 13 for 0 bytes to 128 bytes, but then jumps up to 17s?? For 1kb, it should be much faster to load data in Badger. There's something wrong with the code / measurements.

**Comment by asubiotto** [comment]
Hi @manishrjain. First of all thanks for looking into this.

[This is the code](https://github.com/cockroachdb/cockroach/pull/16343/files#diff-1941d5a816c47bcc8703f82596d234f4R594) that I ran to get the Badger loading time. There was no strong reason for not doing batching either on the RocksDB or Badger end. I wanted to see how it performed in this case and never got around to batching due to the time difference and wanting to get started ASAP on the implementation.

The key-value sizes for our use case are quite variable as they depend on a user-defined schema. A test we run a lot though results in ~`11` bytes per key and ~`128` bytes per value. We batch `4096` bytes before writing.

**Comment by manishrjain** [comment]
Badger would have been a good base for you guys to start for a performant Go native KV store. We've put a lot of work into ensuring Go based Badger can compete against C++ written RocksDB. It's built with performance in mind. I suppose you need transactions, snapshots etc., which could be built on top.

Anyhow. A good way to do benchmarking would be to separately benchmark the loading times and lookups / iteration time. Because most typical workloads have reads >> writes. Very few have writes == reads, or writes > reads.

**Comment by tomByrer** [comment]
> Because most typical workloads have reads >> writes. Very few have writes == reads, or writes > reads.

A use-case I'm researching for is collecting data from users, & the batched reduce for reporting will be only once per day or week.
Also logging tends to write-constantly, read less-often (depends if using real-time dashboard).

**Comment by manishrjain** [comment]
Some more benchmarks against B+-trees: https://blog.dgraph.io/post/badger-lmdb-boltdb/

FWIW, we have an issue to see if folks need transactional support. If that'd be helpful for CockroachDB, let us know.

https://github.com/dgraph-io/badger/issues/230

For a mapreduce style job, we also chose to write directly to files from mappers, then sort it. But, using gnu sort was slower than using a heap merge reading all the map files. Algo written in Go writing final results directly to Badger.

Closing this issue.
